name: qube_analytics_sdk
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/KareemTarekQuebefyn/qube_analytics_sdk

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^11.2.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
